version: '3.3'
services:
  kubecd:
    build: .
    network_mode: host
    volumes:
      - ~/.ssh/:/root/.ssh/
        # - ~/cluster/:/git/
      - ~/.kube/config:/root/.kube/config
    environment:
      - GIT_CLUSTER="git@github.com:trumandk/kube-cluster.git"
      - JUMPSTARTER_USERNAME=admin
      - JUMPSTARTER_PASSWORD=123
